package com.example.mp_2019_android;

import android.support.annotation.NonNull;

public class Endpoint {
    /**** Class variables ****/
    private final String id;
    private final String name;

    Endpoint(String id, String name) {
        /* Generated by the nearby api */
        this.id = id;
        /* Costum endpoint name */
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Endpoint) {
            Endpoint other = (Endpoint) obj;
            return id.equals(other.id);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    @NonNull
    public String toString() {
            return String.format("Endpoint{id=%s, name=%s}", id, name);
    }
}
